package com.example.un_signed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val back: String = "BACK",
    val close: String = "CLOSE",
    val save: String = "SAVE",
    val done: String = "DONE",
    val cancel: String = "CANCEL",
    val next: String = "NEXT",
    val prev: String = "PREV",
    val select: String = "SELECT",
    val edit: String = "EDIT",
    val delete: String = "DELETE",
    val saveAndExit: String = "SAVE & EXIT",

    val selectProfile: String = "SELECT PROFILE",
    val idealProfile: String = "IDEAL PROFILE",
    val customProfile: String = "CUSTOM PROFILE",
    val exportProgress: String = "EXPORT PROGRESS",
    val yearProgress: String = "YEAR PROGRESS",
    val noEvents: String = "no events on record",
    val haveLecture: String = "YOU HAVE A LECTURE",

    val name: String = "NAME",
    val age: String = "AGE",
    val gender: String = "GENDER",
    val weight: String = "WEIGHT",
    val height: String = "HEIGHT",
    val activityLevel: String = "ACTIVITY LEVEL",
    val preferredLanguage: String = "LANGUAGE",
    val male: String = "Male",
    val female: String = "Female",
    val other: String = "Other",

    val education: String = "EDUCATION",
    val health: String = "HEALTH",
    val skill: String = "SKILL",
    val peace: String = "PEACE",
    val focus: String = "FOCUS",
    val settings: String = "SETTINGS",
    val briefing: String = "BRIEFING",
    val compare: String = "COMPARE",
    val tips: String = "TIPS",

    val water: String = "WATER",
    val exercise: String = "EXERCISE",
    val meds: String = "MEDS",
    val junk: String = "JUNK",
    val sleep: String = "SLEEP",
    val habits: String = "HABITS",
    
    val checkUpdate: String = "CHECK FOR UPDATE",
    val updateLog: String = "SHOW UPDATE LOG",
    val haptics: String = "HAPTICS",
    val theme: String = "THEME",
    val system: String = "SYSTEM"
)

val LocEN = AppStrings()

val LocHI = AppStrings(
    back = "पीछे",
    close = "बंद करें",
    save = "सहेजें",
    done = "हो गया",
    cancel = "रद्द करें",
    next = "आगे",
    prev = "पीछे",
    select = "चुनें",
    edit = "बदलें",
    delete = "मिटाएं",
    saveAndExit = "सहेजें और बाहर निकलें",
    selectProfile = "प्रोफ़ाइल चुनें",
    idealProfile = "आदर्श प्रोफ़ाइल",
    customProfile = "कस्टम प्रोफ़ाइल",
    exportProgress = "प्रगति निर्यात करें",
    yearProgress = "वर्ष की प्रगति",
    noEvents = "कोई इवेंट नहीं है",
    haveLecture = "आपकी क्लास है",
    name = "नाम",
    age = "उम्र",
    gender = "लिंग",
    weight = "वजन",
    height = "ऊंचाई",
    activityLevel = "सक्रियता स्तर",
    preferredLanguage = "भाषा",
    male = "पुरुष",
    female = "महिला",
    other = "अन्य",
    education = "शिक्षा",
    health = "स्वास्थ्य",
    skill = "कौशल",
    peace = "शांति",
    focus = "एकाग्रता",
    settings = "सेटिंग्स",
    briefing = "संक्षिप्त विवरण",
    compare = "तुलना",
    tips = "सुझाव",
    water = "पानी",
    exercise = "व्यायाम",
    meds = "दवाएं",
    junk = "जंक फूड",
    sleep = "नींद",
    habits = "आदतें",
    checkUpdate = "अपडेट की जांच करें",
    updateLog = "अपडेट लॉग देखें",
    haptics = "हैप्टिक्स",
    theme = "थीम",
    system = "सिस्टम"
)

val LocRU = AppStrings(
    back = "НАЗАД",
    close = "ЗАКРЫТЬ",
    save = "СОХРАНИТЬ",
    done = "ГОТОВО",
    cancel = "ОТМЕНА",
    next = "ДАЛЕЕ",
    prev = "НАЗАД",
    select = "ВЫБРАТЬ",
    edit = "ИЗМЕНИТЬ",
    delete = "УДАЛИТЬ",
    saveAndExit = "СОХРАНИТЬ И ВЫЙТИ",
    selectProfile = "ВЫБРАТЬ ПРОФИЛЬ",
    idealProfile = "ИДЕАЛЬНЫЙ ПРОФИЛЬ",
    customProfile = "СВОЙ ПРОФИЛЬ",
    exportProgress = "ЭКСПОРТ ПРОГРЕССА",
    yearProgress = "ПРОГРЕСС ГОДА",
    noEvents = "нет записей",
    haveLecture = "У ВАС ЛЕКЦИЯ",
    name = "ИМЯ",
    age = "ВОЗРАСТ",
    gender = "ПОЛ",
    weight = "ВЕС",
    height = "РОСТ",
    activityLevel = "УРОВЕНЬ АКТИВНОСТИ",
    preferredLanguage = "ЯЗЫК",
    male = "Мужчина",
    female = "Женщина",
    other = "Другое",
    education = "ОБРАЗОВАНИЕ",
    health = "ЗДОРОВЬЕ",
    skill = "НАВЫКИ",
    peace = "ПОКОЙ",
    focus = "ФОКУС",
    settings = "НАСТРОЙКИ",
    briefing = "БРИФИНГ",
    compare = "СРАВНЕНИЕ",
    tips = "СОВЕТЫ",
    water = "ВОДА",
    exercise = "УПРАЖНЕНИЯ",
    meds = "ЛЕКАРСТВА",
    junk = "ВРЕДНАЯ ЕДА",
    sleep = "СОН",
    habits = "ПРИВЫЧКИ",
    checkUpdate = "ПРОВЕРИТЬ ОБНОВЛЕНИЕ",
    updateLog = "ЖУРНАЛ ОБНОВЛЕНИЙ",
    haptics = "ВИБРООТКЛИК",
    theme = "ТЕМА",
    system = "СИСТЕМА"
)

val LocZH = AppStrings(
    back = "返回",
    close = "关闭",
    save = "保存",
    done = "完成",
    cancel = "取消",
    next = "下一步",
    prev = "上一步",
    select = "选择",
    edit = "编辑",
    delete = "删除",
    saveAndExit = "保存并退出",
    selectProfile = "选择个人资料",
    idealProfile = "理想资料",
    customProfile = "自定义资料",
    exportProgress = "导出进度",
    yearProgress = "年度进度",
    noEvents = "暂无记录",
    haveLecture = "您有课程",
    name = "姓名",
    age = "年龄",
    gender = "性别",
    weight = "体重",
    height = "身高",
    activityLevel = "活动水平",
    preferredLanguage = "语言",
    male = "男",
    female = "女",
    other = "其他",
    education = "教育",
    health = "健康",
    skill = "技能",
    peace = "宁静",
    focus = "专注",
    settings = "设置",
    briefing = "简报",
    compare = "对比",
    tips = "建议",
    water = "饮水",
    exercise = "运动",
    meds = "药物",
    junk = "垃圾食品",
    sleep = "睡眠",
    habits = "习惯",
    checkUpdate = "检查更新",
    updateLog = "更新日志",
    haptics = "触感反馈",
    theme = "主题",
    system = "系统"
)

val LocJA = AppStrings(
    back = "戻る",
    close = "閉じる",
    save = "保存",
    done = "完了",
    cancel = "キャンセル",
    next = "次へ",
    prev = "前へ",
    select = "選択",
    edit = "編集",
    delete = "削除",
    saveAndExit = "保存して終了",
    selectProfile = "プロファイル選択",
    idealProfile = "理想のプロファイル",
    customProfile = "カスタムプロファイル",
    exportProgress = "進捗をエクスポート",
    yearProgress = "年間の進捗",
    noEvents = "記録なし",
    haveLecture = "講義があります",
    name = "名前",
    age = "年齢",
    gender = "性別",
    weight = "体重",
    height = "身長",
    activityLevel = "活動レベル",
    preferredLanguage = "言語",
    male = "男性",
    female = "女性",
    other = "その他",
    education = "教育",
    health = "健康",
    skill = "スキル",
    peace = "安らぎ",
    focus = "集中",
    settings = "設定",
    briefing = "ブリーfing",
    compare = "比較",
    tips = "ヒント",
    water = "水分",
    exercise = "運動",
    meds = "薬",
    junk = "ジャンクフード",
    sleep = "睡眠",
    habits = "習慣",
    checkUpdate = "更新を確認",
    updateLog = "更新履歴",
    haptics = "触覚フィードバック",
    theme = "テーマ",
    system = "システム"
)

val LocFR = AppStrings(
    back = "RETOUR",
    close = "FERMER",
    save = "SAUVEGARDER",
    done = "TERMINÉ",
    cancel = "ANNULER",
    next = "SUIVANT",
    prev = "PRÉCÉDENT",
    select = "SÉLECTIONNER",
    edit = "MODIFIER",
    delete = "SUPPRIMER",
    saveAndExit = "SAUVER ET QUITTER",
    selectProfile = "CHOISIR PROFIL",
    idealProfile = "PROFIL IDÉAL",
    customProfile = "PROFIL PERSO",
    exportProgress = "EXPORTER PROGRÈS",
    yearProgress = "PROGRÈS DE L'ANNÉE",
    noEvents = "aucun événement",
    haveLecture = "VOUS AVEZ UN COURS",
    name = "NOM",
    age = "ÂGE",
    gender = "SEXE",
    weight = "POIDS",
    height = "TAILLE",
    activityLevel = "NIVEAU D'ACTIVITÉ",
    preferredLanguage = "LANGUE",
    male = "Homme",
    female = "Femme",
    other = "Autre",
    education = "ÉDUCATION",
    health = "SANTÉ",
    skill = "COMPÉTENCE",
    peace = "PAIX",
    focus = "FOCUS",
    settings = "RÉGLAGES",
    briefing = "BRIEFING",
    compare = "COMPARER",
    tips = "CONSEILS",
    water = "EAU",
    exercise = "EXERCICE",
    meds = "MÉDICAMENTS",
    junk = "MALBOUFFE",
    sleep = "SOMMEIL",
    habits = "HABITUDES",
    checkUpdate = "VÉRIFIER MÀJ",
    updateLog = "LOG DE MÀJ",
    haptics = "HAPTIQUE",
    theme = "THÈME",
    system = "SYSTÈME"
)

object Localization {
    val languages = mapOf(
        "en" to "English",
        "hi" to "हिन्दी (Hindi)",
        "bn" to "বাংলা (Bengali)",
        "mr" to "मराठी (Marathi)",
        "te" to "తెలుగు (Telugu)",
        "ta" to "தமிழ் (Tamil)",
        "gu" to "ગુજરાતી (Gujarati)",
        "kn" to "ಕನ್ನಡ (Kannada)",
        "ml" to "മലയാളം (Malayalam)",
        "pa" to "ਪੰਜਾਬੀ (Punjabi)",
        "ru" to "Русский (Russian)",
        "zh" to "中文 (Chinese)",
        "ja" to "日本語 (Japanese)",
        "fr" to "Français (French)",
        "de" to "Deutsch (German)",
        "es" to "Español (Spanish)",
        "it" to "Italiano (Italian)",
        "pt" to "Português (Portuguese)",
        "nl" to "Nederlands (Dutch)"
    )

    fun getStrings(code: String): AppStrings = when (code.lowercase()) {
        "hi" -> LocHI
        "ru" -> LocRU
        "zh" -> LocZH
        "ja" -> LocJA
        "fr" -> LocFR
        // For brevity, I'm mapping other Indian languages to Hindi or English for now
        // In a real scenario, we would have full AppStrings for each.
        else -> LocEN
    }
}

val LocalStrings = staticCompositionLocalOf { AppStrings() }
