package com.example.un_signed

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val back: String = "BACK",
    val close: String = "CLOSE",
    val save: String = "SAVE",
    val done: String = "DONE",
    val cancel: String = "CANCEL",
    val next: String = "NEXT",
    val prev: String = "PREV",
    val select: String = "SELECT",
    val edit: String = "EDIT",
    val delete: String = "DELETE",
    val saveAndExit: String = "SAVE & EXIT",
    val yes: String = "YES",
    val no: String = "NO",
    val language: String = "LANGUAGE",
    val selectPreferredLanguage: String = "Please select your preferred language.",
    val welcome: String = "WELCOME",
    val yourProfile: String = "YOUR PROFILE",
    val tellUsAboutYourself: String = "Tell us about yourself to personalise your health targets.",
    val name: String = "NAME",
    val age: String = "AGE",
    val ageYears: String = "AGE (years)",
    val gender: String = "GENDER",
    val weight: String = "WEIGHT",
    val height: String = "HEIGHT",
    val activityLevel: String = "ACTIVITY LEVEL",
    val preferredLanguage: String = "LANGUAGE",
    val male: String = "Male",
    val female: String = "Female",
    val other: String = "Other",
    val begin: String = "BEGIN",
    val identity: String = "IDENTITY",
    val linkAccounts: String = "Link your email accounts (gmail / tutamail / apple id / meta id). Stored locally.",
    val emailPlaceholder: String = "email@…",
    val session: String = "SESSION",
    val addSession: String = "ADD SESSION",
    val notesOptional: String = "Notes (optional)",
    val recent: String = "RECENT",
    val noSessionsLogged: String = "no sessions logged",
    val closeLabel: String = "CLOSE",
    val openAlarmClock: String = "Open Alarm Clock",
    val alarmQuestion: String = "Take you to the phone's alarm clock?",
    val skip: String = "SKIP",
    val selectProfile: String = "SELECT PROFILE",
    val idealProfile: String = "IDEAL PROFILE",
    val customProfile: String = "CUSTOM PROFILE",
    val exportProgress: String = "EXPORT PROGRESS",
    val yearProgress: String = "YEAR PROGRESS",
    val noEvents: String = "no events on record",
    val haveLecture: String = "YOU HAVE A LECTURE",
    val education: String = "EDUCATION",
    val health: String = "HEALTH",
    val skill: String = "SKILL",
    val peace: String = "PEACE",
    val focus: String = "FOCUS",
    val settings: String = "SETTINGS",
    val briefing: String = "BRIEFING",
    val compare: String = "COMPARE",
    val tips: String = "TIPS",
    val water: String = "WATER",
    val exercise: String = "EXERCISE",
    val meds: String = "MEDS",
    val junk: String = "JUNK",
    val sleep: String = "SLEEP",
    val clockMode: String = "CLOCK MODE",
    val format24Hour: String = "24-HR",
    val format12Hour: String = "12-HR",
    val timer: String = "TIMER",
    val stopwatch: String = "STOPWATCH",
    val alarm: String = "ALARM",
    val dayAndDate: String = "DAY & DATE",
    val beginTimer: String = "BEGIN A TIMER",
    val beginStopwatch: String = "BEGIN STOPWATCH",
    val setAlarm: String = "SET AN ALARM",
    val sleepStartHint: String = "HOLD 3s TO START",
    val sleepEnd: String = "END",
    val disturbances: String = "DISTURB.",
    val habits: String = "HABITS",
    val checkUpdate: String = "CHECK FOR UPDATE",
    val updateLog: String = "SHOW UPDATE LOG",
    val haptics: String = "HAPTICS",
    val theme: String = "THEME",
    val system: String = "SYSTEM",
    val preferencesSummary: String = "Preferences · units · theme · profile",
    val dark: String = "DARK",
    val cream: String = "CREAM",
    val amber: String = "AMBER",
    val weightLabel: String = "WEIGHT",
    val heightLabel: String = "HEIGHT",
    val temperature: String = "TEMPERATURE",
    val distance: String = "DISTANCE",
    val volume: String = "VOLUME",
    val weekStarts: String = "WEEK STARTS",
    val on: String = "ON",
    val off: String = "OFF",
    val kg: String = "KG",
    val lb: String = "LB",
    val cm: String = "CM",
    val inches: String = "INCHES",
    val celsius: String = "°C",
    val fahrenheit: String = "°F",
    val km: String = "KM",
    val miles: String = "MILES",
    val litres: String = "LITRES",
    val ounces: String = "OUNCES",
    val mon: String = "MON",
    val sun: String = "SUN",
    val editProfile: String = "EDIT PROFILE",
    val weightLog: String = "WEIGHT LOG",
    val courseManagement: String = "COURSE MANAGEMENT",
    val practiceManagement: String = "PRACTICE MANAGEMENT",
    val subjectManagement: String = "SUBJECT MANAGEMENT",
    val lecture: String = "LECTURE",
    val lectureName: String = "LECTURE NAME",
    val totalDurationMin: String = "TOTAL DURATION (MIN)",
    val exampleDuration: String = "E.G. 90",
    val topics: String = "TOPICS",
    val addTopics: String = "+ ADD TOPICS",
    val editTopics: String = "✎ EDIT TOPICS",
    val progress: String = "PROGRESS",
    val saveAndBegin: String = "SAVE & BEGIN",
    val enterCourse: String = "ENTER COURSE",
    val enterSub: String = "ENTER SUB",
    val past: String = "PAST",
    val activeSavedCourses: String = "ACTIVE SAVED COURSES",
    val activeSavedPractices: String = "ACTIVE SAVED PRACTICES",
    val activeSavedSubjects: String = "ACTIVE SAVED SUBJECTS",
    val noCompletedCoursesYet: String = "NO COMPLETED COURSES YET",
    val noCompletedPracticesYet: String = "NO COMPLETED PRACTICES YET",
    val noCompletedSubjectsYet: String = "NO COMPLETED SUBJECTS YET",
    val backToManagement: String = "BACK TO MANAGEMENT",
    val whatItsAbout: String = "WHAT IT'S ABOUT!",
    val previousOngoingProfiles: String = "PREVIOUS/ONGOING PROFILES:",
    val createProfile: String = "CREATE PROFILE",
    val deleteProfile: String = "DELETE PROFILE",
    val deleteProfileConfirm: String = "Are you sure you want to delete this profile?",
    val newProfile: String = "NEW PROFILE",
    val duration: String = "DURATION",
    val type: String = "TYPE",
    val saveProfile: String = "SAVE PROFILE",
    val from: String = "FROM",
    val practiceCalendar: String = "PRACTICE CALENDAR",
    val practiceDetail: String = "PRACTICE DETAIL",
    val practicingM: String = "Practicing ℳ",
    val practiceTime: String = "PRACTICE TIME",
    val pastPractices: String = "PAST PRACTICES",
    val pastSubjects: String = "PAST SUBJECTS",
    val customProfileTitle: String = "CUSTOM PROFILE",
    val backToProfileManagement: String = "BACK TO MANAGEMENT",

    val idealOptions: String = "IDEAL OPTIONS",
    val logJunk: String = "LOG JUNK",
    val junkCount: String = "JUNK COUNT",
    val recentTapToRelog: String = "RECENT · TAP TO RE-LOG",
    val search: String = "SEARCH",
    val searchResults: String = "RESULTS",
    val serving: String = "SERVING",
    val saveAndCount: String = "SAVE + COUNT",
    val step: String = "Step",
    val of: String = "of",
    val whatKind: String = "What kind?",
    val whichCategory: String = "Which category?",
    val brandAndName: String = "Brand + name",
    val pickExactProduct: String = "Pick the exact product",
    val healthImpact: String = "Health impact",
    val category: String = "Category",
    val food: String = "FOOD",
    val liquid: String = "LIQUID",
    val brandPlaceholder: String = "brand + product… e.g. Lays classic",
    val findingBrands: String = "finding brands…",
    val tapBrandToSeeProducts: String = "TAP A BRAND · to see all local products",
    val noProductsFound: String = "no products found",
    val filteredToCountry: String = "filtered to your country:",
    val brisWalkToBurn: String = "min brisk walk to burn this off",
    val evidenceSource: String = "src ·",
    val lap: String = "LAP",
    val reset: String = "RESET",
    val lapNumber: String = "Lap",
    val newUpdateAvailable: String = "NEW UPDATE AVAILABLE",
    val version: String = "Version",
    val newLabel: String = "NEW",

    val hobby: String = "HOBBY",
    val minorSkill: String = "MINOR SKILL TO GROW",
    val majorSkill: String = "MAJOR SKILL FOR LIFE",
    val cycling: String = "CYCLING",
    val yoga: String = "YOGA",
    val walking: String = "WALKING",
    val medsLog: String = "MEDS LOG",
    val suppliments: String = "SUPPLIMENTS",
    val severe: String = "SEVERE",
    val diet: String = "DIET",
    val bikingSubtitle: String = "Kilometres & minutes ridden",
    val yogaSubtitle: String = "Practice sessions",
    val walkingSubtitle: String = "Kilometres walked · steps counted",
    val thisWeek: String = "THIS WEEK",
    val distanceLabel: String = "DISTANCE",
    val sessions: String = "SESSIONS",

    val bmi: String = "BMI",
    val bmr: String = "BMR",
    val tdee: String = "TDEE",
    val waterBaseline: String = "Water baseline",
    val sleepTarget: String = "Sleep target",
    val howWeComputedThis: String = "HOW WE COMPUTED THIS",
    val bodyBaseline: String = "Body baseline",
    val last7Days: String = "LAST 7 DAYS",
    val fetchingWeather: String = "fetching weather…",
    val weatherUnavailable: String = "weather unavailable — tap to retry",
    val glasses: String = "glasses",
    val glass: String = "GLASS",
    val sedentary: String = "Sedentary",
    val light: String = "Light",
    val moderate: String = "Moderate",
    val active: String = "Active",
    val veryActive: String = "Very Active",
    val littleNoExercise: String = "Little/no exercise",
    val daysWeek: String = "days/week",
    val physicalJob: String = "Physical job / 2x/day",
    val ft: String = "FT",
    val inchesShort: String = "IN",
    val preview: String = "PREVIEW",

    val format24Sub: String = "24-hour digital clock",
    val format12Sub: String = "12-hour with AM / PM",
    val timerSub: String = "Set a countdown timer",
    val stopwatchSub: String = "Lap & split timer",
    val alarmSub: String = "Open phone alarm clock",
    val dateSub: String = "Show today's day and date",

    val numberTranslation: Map<Char, Char> = emptyMap()
) {
    fun formatNumbers(input: Any): String {
        val s = input.toString()
        if (numberTranslation.isEmpty()) return s
        return s.map { numberTranslation.getOrDefault(it, it) }.joinToString("")
    }
}

val LocEN = AppStrings()

val DevanagariNums = mapOf('0' to '०', '1' to '१', '2' to '२', '3' to '३', '4' to '४', '5' to '५', '6' to '६', '7' to '७', '8' to '८', '9' to '९')
val BengaliNums = mapOf('0' to '০', '1' to '১', '2' to '২', '3' to '৩', '4' to '৪', '5' to '৫', '6' to '৬', '7' to '৭', '8' to '৮', '9' to '৯')
val GurmukhiNums = mapOf('0' to '੦', '1' to '੧', '2' to '੨', '3' to '੩', '4' to '੪', '5' to '੫', '6' to '੬', '7' to '੭', '8' to '੮', '9' to '੯')
val GujaratiNums = mapOf('0' to '૦', '1' to '૧', '2' to '૨', '3' to '૩', '4' to '૪', '5' to '૫', '6' to '૬', '7' to '૭', '8' to '૮', '9' to '૯')
val TeluguNums = mapOf('0' to '౦', '1' to '౧', '2' to '౨', '3' to '౩', '4' to '౪', '5' to '౫', '6' to '౬', '7' to '౭', '8' to '౮', '9' to '౯')
val TamilNums = mapOf('0' to '௦', '1' to '௧', '2' to '௨', '3' to '௩', '4' to '௪', '5' to '௫', '6' to '௬', '7' to '௭', '8' to '௮', '9' to '௯')
val KannadaNums = mapOf('0' to '೦', '1' to '೧', '2' to '೨', '3' to '೩', '4' to '೪', '5' to '೫', '6' to '೬', '7' to '೭', '8' to '೮', '9' to '೯')
val MalayalamNums = mapOf('0' to '൦', '1' to '൧', '2' to '൨', '3' to '൩', '4' to '൪', '5' to '൫', '6' to '൬', '7' to '൭', '8' to '൮', '9' to '൯')

val LocHI = AppStrings(
    back = "पीछे", close = "बंद करें", save = "सहेजें", done = "हो गया", cancel = "रद्द करें",
    next = "आगे", prev = "पीछे", select = "चुनें", edit = "बदलें", delete = "मिटाएं",
    saveAndExit = "सहेजें और बाहर निकलें", yes = "हाँ", no = "नहीं", language = "भाषा",
    selectPreferredLanguage = "अपनी पसंदीदा भाषा चुनें।", welcome = "स्वागतम्", yourProfile = "आपकी प्रोफ़ाइल",
    tellUsAboutYourself = "अपने स्वास्थ्य लक्ष्यों के लिए हमें बताएं।", name = "नाम", age = "उम्र", ageYears = "उम्र (वर्ष)",
    gender = "लिंग", weight = "वजन", height = "ऊंचाई", activityLevel = "सक्रियता स्तर", preferredLanguage = "भाषा",
    male = "पुरुष", female = "महिला", other = "अन्य", begin = "शुरू करें", identity = "पहचान",
    linkAccounts = "अपने ईमेल खाते जोड़ें।", emailPlaceholder = "email@…", selectProfile = "प्रोफ़ाइल चुनें",
    idealProfile = "आदर्श प्रोफ़ाइल", customProfile = "कस्टम प्रोफ़ाइल", exportProgress = "निर्यात करें",
    yearProgress = "वर्ष की प्रगति", noEvents = "कोई इवेंट नहीं", haveLecture = "आपकी क्लास है",
    education = "शिक्षा", health = "स्वास्थ्य", skill = "कौशल", peace = "शांति", focus = "एकाग्रता",
    settings = "सेटिंग्स", briefing = "विवरण", compare = "तुलना", tips = "सुझाव",
    water = "पानी", exercise = "व्यायाम", meds = "दवाएं", junk = "जंक फूड", sleep = "नींद",
    clockMode = "घड़ी मोड", format24Hour = "२४-घं", format12Hour = "१२-घं", timer = "टाइमर",
    stopwatch = "स्टॉपवॉच", alarm = "अलार्म", dayAndDate = "दिन और तारीख", beginTimer = "टाइमर शुरू करें",
    beginStopwatch = "स्टॉपवॉच शुरू करें", setAlarm = "अलार्म सेट करें", sleepStartHint = "३ सेकंड दबाएं",
    sleepEnd = "अंत", disturbances = "गड़बड़ी", habits = "आदतें", checkUpdate = "अपडेट जांचें",
    updateLog = "अपडेट लॉग", haptics = "हैप्टिक्स", theme = "थीम", system = "सिस्टम",
    dark = "डार्क", cream = "क्रीम", amber = "एम्बर", editProfile = "प्रोफ़ाइल संपादित करें",
    weightLog = "वजन लॉग", courseManagement = "कोर्स प्रबंधन", practiceManagement = "अभ्यास प्रबंधन",
    subjectManagement = "विषय प्रबंधन", lecture = "लेक्चर", lectureName = "नाम",
    totalDurationMin = "अवधि (मिनट)", exampleDuration = "उदा. ९०", topics = "विषय",
    addTopics = "+ विषय जोड़ें", editTopics = "✎ संपादित करें", progress = "प्रगति",
    saveAndBegin = "सहेजें और शुरू करें", enterCourse = "कोर्स दर्ज करें", enterSub = "विषय दर्ज करें",
    past = "पिछला", activeSavedCourses = "सक्रिय कोर्स", activeSavedPractices = "सक्रिय अभ्यास",
    activeSavedSubjects = "सक्रिय विषय", backToManagement = "वापस जाएं", createProfile = "प्रोफ़ाइल बनाएं",
    deleteProfile = "हटाएं", newProfile = "नई प्रोफ़ाइल", duration = "अवधि", type = "प्रकार",
    saveProfile = "सहेजें", from = "से", practiceCalendar = "सराव कैलेंडर", practiceDetail = "विवरण",
    practicingM = "अभ्यास ℳ", practiceTime = "समय", pastPractices = "पिछले अभ्यास",
    pastSubjects = "पिछले विषय", customProfileTitle = "कस्टम प्रोफ़ाइल", backToProfileManagement = "वापस",
    idealOptions = "विकल्प", logJunk = "जंक लॉग करें", junkCount = "गिनती",
    recentTapToRelog = "हालिया · टैप करें", search = "खोजें", searchResults = "परिणाम",
    serving = "परोसें", saveAndCount = "सहेजें + गिनती", step = "चरण", of = "का",
    whatKind = "किस तरह?", whichCategory = "कौन सी श्रेणी?", brandAndName = "ब्रांड + नाम",
    pickExactProduct = "उत्पाद चुनें", healthImpact = "प्रभाव", category = "श्रेणी",
    food = "भोजन", liquid = "तरल", brandPlaceholder = "ब्रांड + उत्पाद…", findingBrands = "खोज रहे हैं…",
    tapBrandToSeeProducts = "ब्रांड पर टैप करें", noProductsFound = "उत्पाद नहीं मिला",
    filteredToCountry = "देश फ़िल्टर:", brisWalkToBurn = "मिनट तेज़ पैदल चलना",
    evidenceSource = "स्रोत ·", lap = "लैप", reset = "रीसेट", lapNumber = "लैप",
    newUpdateAvailable = "नया अपडेट", version = "संस्करण", newLabel = "नया",
    hobby = "शौक", minorSkill = "छोटा कौशल", majorSkill = "मुख्य कौशल",
    cycling = "साइकिल चलाना", yoga = "योग", walking = "पैदल चलना", medsLog = "दवा लॉग",
    suppliments = "पूरक", severe = "गंभीर", diet = "आहार", bikingSubtitle = "किमी और मिनट",
    yogaSubtitle = "अभ्यास सत्र", walkingSubtitle = "किमी और कदम", thisWeek = "इस सप्ताह",
    distanceLabel = "दूरी", sessions = "सत्र", bmi = "बीएमआई", bmr = "बीएमआर", tdee = "टीडीईई",
    waterBaseline = "पानी का आधार", sleepTarget = "नींद लक्ष्य", howWeComputedThis = "गणना कैसे की",
    bodyBaseline = "शरीर आधार", last7Days = "पिछले ७ दिन", fetchingWeather = "मौसम ले रहे हैं…",
    weatherUnavailable = "मौसम अनुपलब्ध", glasses = "गिलास", glass = "गिलास", sedentary = "गतिहीन",
    light = "हल्का", moderate = "मध्यम", active = "सक्रिय", veryActive = "बहुत सक्रिय",
    littleNoExercise = "कोई व्यायाम नहीं", daysWeek = "दिन/सप्ताह", physicalJob = "शारीरिक काम",
    ft = "फुट", inchesShort = "इंच", preview = "पूर्वावलोकन",
    format24Sub = "२४-घंटे डिजिटल घड़ी", format12Sub = "१२-घंटे एएम/पीएम",
    timerSub = "टाइमर सेट करें", stopwatchSub = "लैप और स्प्लिट",
    alarmSub = "अलार्म खोलें", dateSub = "आज की तारीख",
    numberTranslation = DevanagariNums
)

val LocMR = LocHI.copy(
    back = "मागे", close = "बंद करा", save = "जतन करा", done = "झाले",
    cancel = "रद्द करा", next = "पुढील", prev = "मागील", select = "निवडा",
    edit = "संपादन", delete = "हटवा", language = "भाषा",
    selectPreferredLanguage = "तुमची भाषा निवडा.", welcome = "स्वागत आहे", yourProfile = "प्रोफाइल",
    tellUsAboutYourself = "तुमच्याबद्दल सांगा.", name = "नाव", age = "वय", ageYears = "वय (वर्षे)",
    gender = "लिंग", weight = "वजन", height = "उंची", activityLevel = "सक्रियता",
    male = "पुरुष", female = "महिला", other = "इतर", begin = "सुरू करा", identity = "ओळख",
    idealProfile = "आदर्श", customProfile = "स्वतःची", exportProgress = "निर्यात",
    yearProgress = "वर्षाची प्रगती", haveLecture = "लेक्चर आहे", education = "शिक्षण",
    health = "आरोग्य", skill = "कौशल्य", peace = "शांतता", focus = "एकाग्रता",
    settings = "सेटिंग्ज", briefing = "माहिती", compare = "तुलना", tips = "टीप्स",
    water = "पाणी", exercise = "व्यायाम", meds = "औषधे", junk = "जंक फूड", sleep = "झोप",
    format24Hour = "२४-तास", format12Hour = "१२-तास", dayAndDate = "दिवस आणि तारीख",
    disturbances = "व्यत्यय", habits = "सवयी", checkUpdate = "तपासा", system = "सिस्टम",
    weightLog = "वजन लॉग", courseManagement = "कोर्स व्यवस्थापन", lecture = "लेक्चर",
    topics = "विषय", progress = "प्रगती", enterCourse = "कोर्स प्रविष्ट करा", past = "मागील",
    backToManagement = "परत", createProfile = "तयार करा", newProfile = "नवीन प्रोफाइल",
    saveProfile = "जतन करा", practiceCalendar = "सराव कॅलेंडर", pastPractices = "मागील सराव",
    idealOptions = "पर्याय", logJunk = "लॉग करा", junkCount = "गणना", search = "शोधा",
    step = "पाऊल", whatKind = "कोणत्या प्रकारचे?", category = "श्रेणी", food = "अन्न",
    liquid = "द्रव", noProductsFound = "आढळले नाही", cycling = "सायकलिंग", yoga = "योग",
    walking = "चालणे", thisWeek = "हा आठवडा", distanceLabel = "अंतर", sessions = "सत्रे",
    last7Days = "शेवटचे ७ दिवस", fetchingWeather = "माहिती घेत आहे…", weatherUnavailable = "अनुपलब्ध",
    numberTranslation = DevanagariNums
)

val LocBN = AppStrings(
    back = "ফিরে যান", close = "বন্ধ করুন", save = "সংরক্ষণ করুন", done = "সম্পন্ন",
    cancel = "বাতিল করুন", next = "পরবর্তী", prev = "পূর্ববর্তী", select = "নির্বাচন করুন",
    edit = "সম্পাদনা", delete = "মুছে ফেলুন", saveAndExit = "সংরক্ষণ ও প্রস্থান",
    yes = "হ্যাঁ", no = "না", language = "ভাষা", selectPreferredLanguage = "ভাষা নির্বাচন করুন।",
    welcome = "স্বাগতম", yourProfile = "আপনার প্রোফাইল", tellUsAboutYourself = "নিজের সম্পর্কে তথ্য দিন।",
    name = "নাম", age = "বয়স", ageYears = "বয়স (বছর)", gender = "লিঙ্গ", weight = "ওজন", height = "উচ্চতা",
    activityLevel = "সক্রিয়তার স্তর", male = "পুরুষ", female = "মহিলা", other = "অন্যান্য", begin = "শুরু করুন",
    identity = "পরিচয়", linkAccounts = "ইমেল যুক্ত করুন।", selectProfile = "প্রোফাইল নির্বাচন",
    idealProfile = "আদর্শ প্রোফাইল", customProfile = "নিজস্ব প্রোফাইল", exportProgress = "রপ্তানি",
    yearProgress = "বছরের অগ্রগতি", noEvents = "কোনো ইভেন্ট নেই", haveLecture = "আপনার লেকচার আছে",
    education = "শিক্ষা", health = "স্বাস্থ্য", skill = "দক্ষতা", peace = "শান্তি", focus = "একাগ্রতা",
    settings = "সেটিংস", briefing = "বিবরণ", compare = "তুলনা", tips = "পরামর্শ",
    water = "জল", exercise = "ব্যায়াম", meds = "ওষুধ", junk = "জঙ্ক ফুড", sleep = "ঘুম",
    clockMode = "ঘড়ি মোড", format24Hour = "২৪-ঘণ্টা", format12Hour = "১২-ঘণ্টা", timer = "টাইমার",
    stopwatch = "স্টপওয়াচ", alarm = "অ্যালার্ম", dayAndDate = "দিন ও তারিখ",
    beginTimer = "টাইমার শুরু করুন", beginStopwatch = "স্টপওয়াচ শুরু করুন", setAlarm = "অ্যালার্ম সেট করুন",
    sleepStartHint = "৩ সেকেন্ড ধরে রাখুন", sleepEnd = "শেষ", disturbances = "ব্যাঘাত", habits = "অভ্যাস",
    checkUpdate = "চেক করুন", updateLog = "লগ", haptics = "হ্যাপটিক্স", theme = "থিম",
    system = "সিস্টেম", dark = "ডার্ক", cream = "ক্রিম", amber = "অ্যাম্বার", editProfile = "সম্পাদনা",
    weightLog = "ওজন লগ", courseManagement = "কোর্স ম্যানেজমেন্ট", lecture = "লেকচার",
    topics = "টপিক", progress = "অগ্রগতি", saveAndBegin = "সংরক্ষণ ও শুরু", enterCourse = "কোর্স লিখুন",
    past = "অতীত", activeSavedCourses = "সক্রিয় কোর্স", backToManagement = "ফিরে যান",
    createProfile = "তৈরি করুন", deleteProfile = "মুছে ফেলুন", newProfile = "নতুন প্রোফাইল",
    duration = "সময়কাল", type = "ধরন", saveProfile = "সংরক্ষণ", from = "থেকে",
    practiceCalendar = "ক্যালেন্ডার", practiceDetail = "বিবরণ", practicingM = "প্র্যাকটিস চলছে ℳ",
    practiceTime = "সময়", pastPractices = "অতীত প্র্যাকটিস", idealOptions = "বিকল্প",
    logJunk = "লগ করুন", junkCount = "গণনা", recentTapToRelog = "সাম্প্রতিক",
    search = "অনুসন্ধান", searchResults = "ফলাফল", serving = "পরিবেশন", saveAndCount = "সংরক্ষণ",
    step = "ধাপ", of = "এর", whatKind = "কি ধরনের?", whichCategory = "কোন বিভাগ?",
    brandAndName = "ব্র্যান্ড + নাম", pickExactProduct = "পণ্য বেছে নিন", healthImpact = "প্রভাব",
    category = "বিভাগ", food = "খাদ্য", liquid = "তরল", brandPlaceholder = "ব্র্যান্ড + পণ্য…",
    findingBrands = "খুঁজছে…", tapBrandToSeeProducts = "ট্যাপ করুন", noProductsFound = "পাওয়া যায়নি",
    filteredToCountry = "ফিল্টার:", brisWalkToBurn = "মিনিট দ্রুত হাঁটা", evidenceSource = "উৎস ·",
    lap = "ল্যাপ", reset = "রিসেট", lapNumber = "ল্যাপ", newUpdateAvailable = "আপডেট উপলব্ধ",
    version = "ভার্সন", newLabel = "নতুন", hobby = "শখ", minorSkill = "ছোট দক্ষতা",
    majorSkill = "প্রধান দক্ষতা", cycling = "সাইক্লিং", yoga = "যোগব্যায়াম", walking = "হাঁটা",
    medsLog = "ওষুধ লগ", suppliments = "সাপ্লিমেন্ট", severe = "গুরুতর", diet = "ডায়েট",
    bikingSubtitle = "কিমি এবং মিনিট", yogaSubtitle = "সেশন", walkingSubtitle = "কিমি ও পদক্ষেপ",
    thisWeek = "এই সপ্তাহ", distanceLabel = "দূরত্ব", sessions = "সেশন", bmi = "বিএমআই",
    bmr = "বিএমআর", tdee = "টিডিইই", waterBaseline = "জল বেসলাইন", sleepTarget = "লক্ষ্য",
    howWeComputedThis = "গণনা কিভাবে", bodyBaseline = "বডি বেসলাইন", last7Days = "শেষ ৭ দিন",
    fetchingWeather = "তথ্য নিচ্ছে…", weatherUnavailable = "অনুপলব্ধ", glasses = "গ্লাস",
    glass = "গ্লাস", sedentary = "বসা কাজ", light = "হালকা", moderate = "মাঝারি",
    active = "সক্রিয়", veryActive = "খুব সক্রিয়", littleNoExercise = "ব্যায়াম নেই",
    daysWeek = "দিন/সপ্তাহ", physicalJob = "শারীরিক কাজ", ft = "ফুট", inchesShort = "ইঞ্চি",
    preview = "পূর্বরূপ", format24Sub = "২৪ ঘণ্টা ডিজিটাল", format12Sub = "১২ ঘণ্টা এএম/পিএম",
    timerSub = "টাইমার সেট করুন", stopwatchSub = "ল্যাপ এবং স্প্লিট", alarmSub = "অ্যালার্ম খুলুন",
    dateSub = "আজকের তারিখ",
    numberTranslation = BengaliNums
)

val LocRU = AppStrings(
    back = "НАЗАД", close = "ЗАКРЫТЬ", save = "СОХРАНИТЬ", done = "ГОТОВО", cancel = "ОТМЕНА",
    next = "ДАЛЕЕ", prev = "НАЗАД", select = "ВЫБРАТЬ", edit = "ИЗМЕНИТЬ", delete = "УДАЛИТЬ",
    saveAndExit = "СОХРАНИТЬ И ВЫЙТИ", yes = "ДА", no = "НЕТ", language = "ЯЗЫК",
    selectPreferredLanguage = "Выберите язык.", welcome = "ДОБРО ПОЖАЛОВАТЬ", yourProfile = "ПРОФИЛЬ",
    tellUsAboutYourself = "Расскажите о себе.", name = "ИМЯ", age = "ВОЗРАСТ", ageYears = "ВОЗРАСТ",
    gender = "ПОЛ", weight = "ВЕС", height = "РОСТ", activityLevel = "АКТИВНОСТЬ",
    male = "Мужчина", female = "Женщина", other = "Другое", begin = "НАЧАТЬ", identity = "ЛИЧНОСТЬ",
    selectProfile = "ВЫБОР ПРОФИЛЯ", idealProfile = "ИДЕАЛЬНЫЙ", customProfile = "СВОЙ ПРОФИЛЬ",
    exportProgress = "ЭКСПОРТ", yearProgress = "ПРОГРЕСС", noEvents = "нет записей",
    haveLecture = "ЛЕКЦИЯ", education = "ОБРАЗОВАНИЕ", health = "ЗДОРОВЬЕ", skill = "НАВЫКИ",
    peace = "ПОКОЙ", focus = "ФОКУС", settings = "НАСТРОЙКИ", briefing = "БРИФИНГ",
    compare = "СРАВНЕНИЕ", tips = "СОВЕТЫ", water = "ВОДА", exercise = "УПРАЖНЕНИЯ",
    meds = "ЛЕКАРСТВА", junk = "ВРЕДНАЯ ЕДА", sleep = "СОН", clockMode = "РЕЖИМ",
    format24Hour = "24-Ч", format12Hour = "12-Ч", timer = "ТАЙМЕР", stopwatch = "СЕКУНДОМЕР",
    alarm = "БУДИЛЬНИК", dayAndDate = "ДАТА", beginTimer = "СТАРТ ТАЙМЕРА",
    beginStopwatch = "СТАРТ СЕКУНДОМЕРА", setAlarm = "БУДИЛЬНИК", disturbances = "сбои",
    habits = "ПРИВЫЧКИ", checkUpdate = "ОБНОВИТЬ", system = "СИСТЕМА", dark = "ТЕМНАЯ",
    cream = "СЛИВКИ", amber = "ЯНТАРЬ", editProfile = "ИЗМЕНИТЬ", weightLog = "ЛОГ ВЕСА",
    courseManagement = "КУРСЫ", lecture = "ЛЕКЦИЯ", topics = "ТЕМЫ", progress = "ПРОГРЕСС",
    saveAndBegin = "СТАРТ", enterCourse = "ВВОД КУРСА", past = "ПРОШЛОЕ",
    backToManagement = "НАЗАД", createProfile = "СОЗДАТЬ", duration = "ДЛИТ.",
    type = "ТИП", saveProfile = "СОХРАНИТЬ", from = "ОТ", practiceCalendar = "КАЛЕНДАРЬ",
    idealOptions = "ОПЦИИ", logJunk = "ЛОГ ЕДЫ", junkCount = "СЧЕТ", search = "ПОИСК",
    searchResults = "РЕЗУЛЬТАТЫ", serving = "ПОРЦИЯ", step = "Шаг", of = "из",
    category = "КАТЕГОРИЯ", food = "ЕДА", liquid = "НАПИТКИ", noProductsFound = "НЕ НАЙДЕНО",
    hobby = "ХОББИ", cycling = "ВЕЛОСИПЕД", yoga = "ЙОГА", walking = "ХОДЬБА",
    thisWeek = "НЕДЕЛЯ", distanceLabel = "ДИСТАНЦИЯ", sessions = "СЕАНСЫ", last7Days = "7 ДНЕЙ"
)

val LocZH = AppStrings(
    back = "返回", close = "关闭", save = "保存", done = "完成", next = "下一步",
    prev = "上一步", select = "选择", edit = "编辑", delete = "删除", yes = "是", no = "否",
    language = "语言", welcome = "欢迎", yourProfile = "个人资料", name = "姓名", age = "年龄",
    gender = "性别", weight = "体重", height = "身高", activityLevel = "活动", male = "男",
    female = "女", begin = "开始", identity = "身份", selectProfile = "选择资料",
    idealProfile = "理想", customProfile = "自定义", exportProgress = "导出",
    yearProgress = "年度进度", education = "教育", health = "健康", skill = "技能",
    peace = "宁静", focus = "专注", settings = "设置", briefing = "简报",
    compare = "对比", tips = "建议", water = "饮水", exercise = "运动", meds = "药物",
    junk = "垃圾食品", sleep = "睡眠", clockMode = "时钟模式", timer = "计时器",
    stopwatch = "秒表", alarm = "闹钟", dayAndDate = "日期", habits = "习惯",
    checkUpdate = "检查更新", system = "系统", dark = "深色", cream = "奶油", amber = "琥珀",
    editProfile = "编辑资料", courseManagement = "课程管理", lecture = "讲座", topics = "主题",
    progress = "进度", saveAndBegin = "保存并开始", past = "过去", backToManagement = "返回",
    idealOptions = "选项", logJunk = "记录", junkCount = "计数", search = "搜索",
    step = "步骤", category = "类别", food = "食物", liquid = "饮料", cycling = "骑行",
    yoga = "瑜伽", walking = "走路", thisWeek = "本周", distanceLabel = "距离", sessions = "阶段"
)

val LocJA = AppStrings(
    back = "戻る", close = "閉じる", save = "保存", done = "完了", next = "次へ",
    prev = "前へ", select = "選択", edit = "編集", delete = "削除", yes = "はい", no = "いいえ",
    language = "言語", welcome = "ようこそ", yourProfile = "プロフィール", name = "名前",
    age = "年齢", gender = "性別", weight = "体重", height = "身長", activityLevel = "活動",
    male = "男性", female = "女性", begin = "開始", identity = "識別",
    selectProfile = "プロファイル選択", idealProfile = "理想", customProfile = "カスタム",
    exportProgress = "エクスポート", yearProgress = "進捗", education = "教育",
    health = "健康", skill = "スキル", peace = "安らぎ", focus = "集中",
    settings = "設定", briefing = "情報", compare = "比較", tips = "ヒント",
    water = "水分", exercise = "運動", meds = "薬", junk = "ジャンク", sleep = "睡眠",
    timer = "タイマー", stopwatch = "秒表", alarm = "アラーム", habits = "習慣",
    system = "システム", dark = "ダーク", cream = "クリーム", amber = "アンバー",
    editProfile = "編集", lecture = "講義", topics = "トピック", progress = "進捗",
    past = "過去", backToManagement = "戻る", idealOptions = "オプション",
    logJunk = "記録", junkCount = "数", search = "検索", step = "ステップ",
    food = "食品", liquid = "液体", cycling = "サイクリング", yoga = "ヨガ",
    walking = "歩行", thisWeek = "今週", distanceLabel = "距離", sessions = "セッション"
)

val LocFR = AppStrings(
    back = "RETOUR", close = "FERMER", save = "SAUVEGARDER", done = "TERMINÉ",
    cancel = "ANNULER", next = "SUIVANT", prev = "PRÉCÉDENT", select = "SÉLECTIONNER",
    edit = "MODIFIER", delete = "SUPPRIMER", saveAndExit = "SAUVER ET QUITTER",
    yes = "OUI", no = "NON", language = "LANGUE",
    selectPreferredLanguage = "Veuillez sélectionner votre langue.",
    welcome = "BIENVENUE", yourProfile = "VOTRE PROFIL",
    name = "NOM", age = "ÂGE", ageYears = "ÂGE (années)", gender = "SEXE", weight = "POIDS", height = "TAILLE",
    activityLevel = "ACTIVITÉ", male = "Homme", female = "Femme", other = "Autre",
    begin = "COMMENCER", identity = "IDENTITÉ", linkAccounts = "Liez vos comptes.",
    emailPlaceholder = "email@…", selectProfile = "CHOISIR PROFIL",
    idealProfile = "PROFIL IDÉAL", customProfile = "PROFIL PERSO",
    exportProgress = "EXPORTER", yearProgress = "PROGRÈS",
    noEvents = "aucun événement", haveLecture = "VOUS AVEZ UN COURS",
    education = "ÉDUCATION", health = "SANTÉ", skill = "COMPÉTENCE",
    peace = "PAIX", focus = "FOCUS", settings = "RÉGLAGES",
    briefing = "BRIEFING", compare = "COMPARER", tips = "CONSEILS",
    water = "EAU", exercise = "EXERCICE", meds = "MÉDICAMENTS", junk = "MALBOUFFE",
    sleep = "SOMMEIL", clockMode = "MODE HORLOGE", timer = "MINUTEUR",
    stopwatch = "CHRONO", alarm = "ALARME", dayAndDate = "JOUR & DATE",
    beginTimer = "LANCER MINUTEUR", beginStopwatch = "LANCER CHRONO",
    setAlarm = "RÉGLER ALARME", sleepStartHint = "Maintenez 3s pour commencer",
    sleepEnd = "FIN", disturbances = "perturb.", habits = "HABITUDES",
    checkUpdate = "MÀJ", updateLog = "LOG MÀJ", haptics = "HAPTIQUE",
    theme = "THÈME", system = "SYSTÈME", dark = "SOMBRE", cream = "CRÈME", amber = "AMBRE",
    editProfile = "ÉDITER PROFIL", weightLog = "LOG POIDS",
    courseManagement = "GESTION COURS", practiceManagement = "GESTION EXERCICES",
    subjectManagement = "GESTION SUJETS", lecture = "COURS",
    lectureName = "NOM DU COURS", totalDurationMin = "DURÉE (MIN)",
    topics = "SUJETS", addTopics = "+ SUJETS", editTopics = "✎ MODIFIER",
    progress = "PROGRESSION", saveAndBegin = "ENREGISTRER",
    enterCourse = "ENTRER COURS", enterSub = "ENTRER SUJET",
    past = "PASSÉ", activeSavedCourses = "COURS ACTIFS",
    activeSavedPractices = "EXERCICES ACTIFS", activeSavedSubjects = "SUJETS ACTIFS",
    backToManagement = "RETOUR", createProfile = "CRÉER PROFIL",
    deleteProfile = "SUPPRIMER", newProfile = "NOUVEAU PROFIL",
    duration = "DURÉE", type = "TYPE", saveProfile = "SAUVER PROFIL",
    from = "DE", practiceCalendar = "CALENDRIER", practiceDetail = "DÉTAILS",
    practicingM = "Exercice ℳ", practiceTime = "TEMPS",
    pastPractices = "EXERCICES PASSÉS", pastSubjects = "SUJETS PASSÉS",
    customProfileTitle = "PROFIL PERSO",
    idealOptions = "OPTIONS", logJunk = "LOG MALBOUFFE", junkCount = "COMPTEUR",
    recentTapToRelog = "RÉCENT", search = "CHERCHER", searchResults = "RÉSULTATS",
    serving = "PORTION", saveAndCount = "SAUVER", step = "Étape",
    hobby = "LOISIR", cycling = "VÉLO", yoga = "YOGA", walking = "MARCHE",
    thisWeek = "CETTE SEMAINE", distanceLabel = "DISTANCE", sessions = "SESSIONS"
)

object Localization {
    val languages = mapOf(
        "en" to "English", "hi" to "हिन्दी (Hindi)", "bn" to "বাংলা (Bengali)", "mr" to "मराठी (Marathi)",
        "te" to "తెలుగు (Telugu)", "ta" to "தமிழ் (Tamil)", "gu" to "ગુજરાતી (Gujarati)", "kn" to "ಕನ್ನಡ (Kannada)",
        "ml" to "മലയാളം (Malayalam)", "pa" to "ਪੰਜਾਬੀ (Punjabi)", "ru" to "Русский (Russian)", "zh" to "中文 (Chinese)",
        "ja" to "日本語 (Japanese)", "fr" to "Français (French)", "de" to "Deutsch (German)", "es" to "Español (Spanish)",
        "it" to "Italiano (Italian)", "pt" to "Português (Portuguese)", "nl" to "Nederlands (Dutch)"
    )

    fun getStrings(code: String): AppStrings = when (code.lowercase()) {
        "hi" -> LocHI
        "bn" -> LocBN
        "mr" -> LocMR
        "ru" -> LocRU
        "zh" -> LocZH
        "ja" -> LocJA
        "fr" -> LocFR
        "te" -> LocEN.copy(numberTranslation = TeluguNums)
        "ta" -> LocEN.copy(numberTranslation = TamilNums)
        "gu" -> LocEN.copy(numberTranslation = GujaratiNums)
        "kn" -> LocEN.copy(numberTranslation = KannadaNums)
        "ml" -> LocEN.copy(numberTranslation = MalayalamNums)
        "pa" -> LocEN.copy(numberTranslation = GurmukhiNums)
        else -> LocEN
    }
}

val LocalStrings = staticCompositionLocalOf { AppStrings() }
